export const COUNTRIES = 'https://dev5.itcation.com/api/countries'
export const PROJECTS = 'https://dev5.itcation.com/api/projects'
export const PROJECT = 'https://dev5.itcation.com/api/projects/'
export const LOGOUT = 'https://dev5.itcation.com/api/auth/logout'
export const PROFILE = 'https://dev5.itcation.com/api/auth/profile'
export const LOGIN = 'https://dev5.itcation.com/api/auth/login'
export const REGISTER = 'https://dev5.itcation.com/api/auth/register'